events{

}

http{

    upstream backend {
        server server1:7000;
        server server2:7000;
        # server server3:7000;
    }

    server{
        listen 80;
        location /{
            # return 200 "hello from Darshan";    use nginx as a web server 
            # use nginx as a load balancer
            proxy_pass http://backend;

        }
    }
}

